---
dist: xenial
sudo: required
language: python
python:
  - "3.7"
install:
  - pip install vim-vint
script:
  - vint --color --style plugin/vim-cheatsheet.vim
notifications:
  email: false
  slack:
    secure: jHNaZet6Kg0G0Uw7PKD/C2xKcpdsmLYg7Sb+5cZNy35CxrNgCJRyAMJ5a7/Pv/FwIiLx1WQ6FfEz3sgoE51xPNu9ilkON45qReweC4FJpPImoAFXJywi5N79IM1YGIuMXJYkl/oytHiO1+nTkp/MTB692DqELMuGMVeNwzWHo0XrOkhtp40WZcbMjZHC8kDBZQf01aPSMpqEP5XpYmtlZBd3kKZjQdW7PJ5+owRFdwqtsjQkaHtbkDtmm31UjIv06aqj0R/PWimNlcEPcpTsnf0LkwZjgLeuh2TsoPyIhBRHbsly22cDP5DQfPRQ1xjg+TG6RriOuVHRv2eSB4N6wNb87yKcsa1TBdiaru3Lz+QBfLgzWvK99NdAYMQcgcVxyUqDoBmfIZh38N3WQ9jA08X4t713ScC+wD/xh8ZNVFabVCURDIG7eOrLMq38DEbfvQxjaWUxO5b/zvUODJdHjtrkCGm15dJGdDDp6ijx03LBpQWk3MFC6e6Z78d2eQjSOnSWAWMFHsdj+tVrEDOA5snnptCl//Py90n0bo/fe3S0jFbK1MhXo3uH0GCOt2QU6GjIsb/5KL5G/gLXyMuRoRjfNTjwuTRGShD4LeEJ6wrsBXI8x2oSArFDnk+s9ufTaB6jYXDjHkBLWcPymEi70bYfNi5id3nHWIaFXLcduCE=
